### ISSUE TITLE
Feature: News

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#29]
Als Administrator möchte ich Nutzer über neue Inhalte informieren können. Eine News sollte aus Bild/Video/Animation(JSON), Text und CTA bestehen, wobei nur der Text ein Pflichtfeld sein sollte. 

Video und Animation zweitraging. Bitte zunächst Bild umsetzen. 

Als Nutzer möchte ich über eine mir bekannte Stelle in der Navigation auf die News zugreifen können. 

Als Nutzer möchte ich darauf hingewiesen werden wenn es neue News gibt. 

**News anlegen**
- [ ] Video und Animation zweitraging. Bitte zunächst Bild umsetzen. 

**Navigation**
- [x] News-Icon ist in Space-Übersicht und im Space sichtbar
- [x] Im Drop-Down werden die 3 obersten News angezeigt
- [x] News-Alert so lange aktiv, bis Nutzer auf die Glocke geklickt hat und das Dropdown geöffnet hat

**News Übersichtsseite**
- [x] Unter Präferenzen werden zum Einen angelegte Kategorien angezeigt, wobei nur Kategorien die vergeben sind angezeigt werden und zum Anderen die Spaces
- [x] Top News, ist die News die im Backend ganz oben steht (also nicht unbedingt die aktuellste)
- [x] Bei Klick auf "Mehr Laden" werden 6 weitere News geladen

**Backend**
- [x] Neuer Reiter "Neuigkeiten" unter "Administration" > "Funktionen" nach "Mein Markenportal"
- [x] Hier kann das News Feature zunächst aktiviert und deaktiviert werden
- [x] Wird es aktiviert, können die News auf dieser Seite verwaltet werden
- [x] Button "Kategorien bearbeiten" neben "News hinzufügen" ergänzen
- [x] Hier können neue Kategorien hinzugefügt und gelöscht werden
- [x] Wird eine verwendete Kategorie gelöscht, wird der Nutzer mittels eines Pop-Ups darauf hingewiesen das die Kategorie sich in Verwendung befindet und er muss bestätigen, dass er sich sicher ist. Die News mit der Kategorie werden allerdings nicht gelöscht

**ToDos**
- [x] Label für news_title & news_text
- [x] news_text sollte MDE sein. Es müssen hier auch Links gesetzt werden können
- [x] Zugriff sollte per Default für alle angehakt sein
- [x] published für Deutsch umbenennen in "Veröffentlicht" und prominenter als Button platzieren

**Design**
https://share.goabstract.com/17e26997-844a-4177-a761-a26b63506b19?collectionLayerId=89990855-9f5e-488f-9abd-b392644ad27f&mode=design&sha=5d4548fef041b68f8f6f00ad14748c6115a611cd

**Job**
VKB-21261 / Markenportal Refresh

**Comment by karatektus** [comment]
So far so good: Todos @ChristinaGu @pmdevelopment :

Sortieren fixen (funktioniert nicht mehr wenn akkordeon geöffnet wurde) <- sven?

Simple MDE internal link fixen <- sven internal link ohne space? feature ausschalten?

Newspref dropdown schließt sich beim an und abhaken (wenn man auf die checkbox direkt klickt)

Neue Spaces für alle automatisch aktivieren? <- Christina?

**Comment by ChristinaGu** [comment]
- [ ] Kompletter News-Teaser sollte klickbar sein
- [ ] Zeichenzahl bei Hero Teaser auf 200
- [ ] Kategorie als badge (<span class="badge badge-primary fs-8 fw-bolder"">Corporate Design</span>)
- [ ] Spaces statt Kategorie hinter Datum und Positionierung anpassen, siehe Screenshot
- [ ] Hintergrundfarbe hinter Bild und Text, siehe Screenshot
- [ ] Kein Padding bei den Bildern

<img width="1440" alt="Bildschirmfoto 2021-11-08 um 12 27 45" src="https://user-images.githubusercontent.com/8007132/140734393-81491da5-e3da-402c-aa47-f3b800afeca1.png">

**Comment by karatektus** [comment]
Noch bekannte Fehler:

- [ ] Sortieren noch defekt sobald das Akkordeon einmal geöffnet wurde (auch wenns wieder zu gemacht wird)
- [ ] SimpleMDE internal link tut nich

**Comment by laurahll** [comment]
@ChristinaGu Ich hab es mir jetzt erst angesehen, sorry
ich habe noch folgende Anmerkungen.

1. Wir hatten den Hover Zustand von den Buttons nicht definiert. Aber in der Regel wird die Farbe **heller**. Gleiches bei Links. @ChristinaGu Für den Konzern wurde das noch nie definiert , oder?
2. Wenn es keine News zu den ausgewählten Präferenzen gibt, dann sollte da trotzdem irgendwas stehen. Vielleicht „Keine Neuigkeiten zu diesen Präferenzen verfügbar“? Ähnlich wie leere Seiten, da steht doch auch ein Hinweis.
3. Das Präferenzen Popup ist der lang und passt bei mir nicht in den Viewport. Dadurch wird die Seite sogar länger und der Footer hängt dann halb in der Mitte. Am besten die Kategorien eine Schriftgröße kleiner.
![506EA969-4228-4830-BA35-3BF2C727FBAD_1_105_c](https://user-images.githubusercontent.com/66866462/140926682-6e69838a-7ddb-4963-ab30-08c49229bc47.jpeg)

4. Könnte man im Backend beim Erstellen noch ein Charakter limit für die Überschrift hinzufügen? Bei langen Überschriften bricht auch der Titel im Akkordion über die Icons.
![DD036D5E-F79B-4452-A5D7-5DCC423010B7_4_5005_c](https://user-images.githubusercontent.com/66866462/140926730-e285fe50-22d0-4812-9524-76e6bb797770.jpeg)

5. In dem Präferenzen Modal wäre vielleicht noch ein zusätzlicher Button „Zurücksetzen“ hilfreich. Sind doch sehr viele Kategorien und damit könnte man wieder alle Präferenzen anhaken.
6. Ich hab eine neue News erstellt und wollte im Text Editor einen Link zufügen. Da hängt es sich auf und ich sehe nur diese Punkt Animation.
7. Wenn eine neue News hinzugefügt wird, wäre es gut wenn das Akkordion direkt aufgeht.

**Comment by ChristinaGu** [comment]
**Sven**
- [ ]  Sortieren noch defekt sobald das Akkordeon einmal geöffnet wurde (auch wenns wieder zu gemacht wird)
- [ ]  SimpleMDE internal link tut nich

**ToDos Paul**
- [ ] Wenn es keine News zu den ausgewählten Präferenzen gibt, dann sollte da trotzdem irgendwas stehen. Vielleicht „Keine Neuigkeiten zu diesen Präferenzen verfügbar“? Ähnlich wie leere Seiten, da steht doch auch ein Hinweis.
- [ ] Präferenzen Pop-Up breiter und Schrift kleiner

**Comment by pmdevelopment** [comment]
Offene Todos werden in neue Issues verlagert.
