### ISSUE TITLE
Downloadcenter

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#408]
**ToDos**
- [x] Bug: Nach Sucheingabe verschwindet Table Head 
- [x] Pflichtenheft bzw Prios klären: was setzen wir im vorhanden Budget um?
- [x] Nur Downloads der Spaces zeigen, auf die Nutzer Zugriff hat
- [x] Sortierung und Filterung umsetzen
- [x] Filter nach Dateityp
- [x] Filter nach Tags
- [x] Previews umsetzen
- [x] Überschrift und Einleitung? (siehe Kommentar)
- [x] Navigation dauerhaft aufklappen, wenn mehrere Spaces vorhanden

**Erster Designentwurf**
https://www.figma.com/file/4lvLk6rYqvKWJgf5hcjIsH/wirHub-Components-%26-Prototype?node-id=495%3A5514&t=0Kwb8p5HU58okoNH-1

**Jobnummmer**
K**-22203 / Download-Center_BrandNet

**Budget**
6 Tage Programmierung 
2 Tage Design

**Comment by ChristinaGu** [comment]
Erster Entwurf bis zum 16.12.

**Comment by pmdevelopment** [comment]
Folgende Texte wurden gewünscht:

Bitte die Überschrift einsetzen, für DE: Download-Center und für EN: Download Center
Bitte eine kurze Einleitung ergänzen:
Hier findest Du alle Dateien zum Download. Lade Dateien einzeln herunter oder nutze die Warenkorb-Funktion für einen Sammel-Download mit einem Klick
Here you can download all files. Download files individually or use the shopping cart function for a collective download with just one click

Ticket #8167

**Comment by ChristinaGu** [comment]
@LisaS13 könntest du für die Schnellsuche noch eine Close-Funktion ergänzen? Aktuell kann man den Suchschlitz nur schließen, indem man nochmal auf das Such-Icon klickt
