### ISSUE TITLE
Theme Konfigurator

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirHub-doc#52]
Ich würde gerne das Thema Theme Konfigurator angehen. Im Moment können nur Entwickler das Design eines wirHubs anpassen, indem sie unter Einstellungen > Administration > Frontend ein Theme bzw. dessen SCSS und SCSS Variablen bearbeiten. 

In Zukunft soll auch ein Administrator in der Lage sein über einen Konfigurator zumindest die wichtigsten Styles anpassen zu können. Ich finde pitch.io hat das z.B. sehr gut gelöst und dort funktioniert es ähnlich wie unser Quick-Edit. Man sieht links die Styles und kann sie rechts bearbeiten. Beim Bearbeiten sieht man live wie es sich auswirkt. 
![beispiel-pitch-io](https://user-images.githubusercontent.com/8007132/122978057-5d5f1680-d396-11eb-9ad4-e71fac8d4862.png)

Ich habe hier schon mal eine Seite mit allen wichtigen Styles angelegt
https://hallo.wirhub.de/spielwiese/style/category/konfigurator
![hallo wirhub de_spielwiese_style_category_konfigurator](https://user-images.githubusercontent.com/8007132/122979095-71efde80-d397-11eb-950a-27a09509837a.png)

**ToDos**
- [ ] Definieren welche Einstellungsmöglichkeiten es genau gibt @ChristinaGu 
- [ ] Designvorschlag für Konfigurator erstellen (wäre wie gesagt verortet unter Einstellungen > Administration > Frontend (habe dir bei hallo.wirhub.de Admin-Rechte gegeben. Dort solltest du es sehen können) @estherconstantin 
- [ ] Einstellungen > Administration > Frontend umbenennen in "Theme anpassen" @pmdevelopment 
- [ ] Folgende Unterpunkte hinzufügen (als Flyout wie im Hauptmenü nicht als Tabs): Konfigurator, Themes, Login Screen @pmdevelopment

**Comment by ChristinaGu** [comment]
[ueberesicht-einstellungen.xlsx](https://github.com/wirDesign-communication-AG/wirHub-doc/files/6696650/ueberesicht-einstellungen.xlsx)
